from api.user_permissions_api import router as user_permissions_router
from api.employees_api import router as employees_router
from api.clients_api import router as clients_router
from api.global_study_policies_api import router as global_study_policies_router
from api.study_agency_info_api import router as study_agency_info_router
from api.training_courses_api import router as training_courses_router
from api.activity_info_api import router as activity_info_router
from api.activity_bookings_api import router as activity_bookings_router
from api.faq_api import router as faq_router
from api.sales_results_api import router as sales_results_router
from api.daily_reports_api import router as daily_reports_router
from api.monthly_goals_api import router as monthly_goals_router
from api.students_api import router as students_router
from api.student_face_records_api import router as student_face_records_router
from api.student_leaves_api import router as student_leaves_router
from api.student_complaints_api import router as student_complaints_router
from api.student_chat_logs_api import router as student_chat_logs_router
from api.student_photos_api import router as student_photos_router
from api.exams_api import router as exams_router
from api.student_grades_api import router as student_grades_router
from api.knowledge_base_overseas_api import router as knowledge_base_overseas_router
from api.classes_api import router as classes_router
