from models.user_permissions import UserPermissions
from models.employees import Employees
from models.clients import Clients
from models.global_study_policies import GlobalStudyPolicies
from models.study_agency_info import StudyAgencyInfo
from models.training_courses import TrainingCourses
from models.activity_info import ActivityInfo
from models.activity_bookings import ActivityBookings
from models.faq import Faq
from models.sales_results import SalesResults
from models.daily_reports import DailyReports
from models.monthly_goals import MonthlyGoals
from models.students import Students
from models.student_face_records import StudentFaceRecords
from models.student_leaves import StudentLeaves
from models.student_complaints import StudentComplaints
from models.student_chat_logs import StudentChatLogs
from models.student_photos import StudentPhotos
from models.exams import Exams
from models.knowledge_base_overseas import KnowledgeBaseOverseas
from models.classes import Classes
